### ISSUE TITLE
서비스 자동실행

### ISSUE THREAD

**Issue by Frentree** [Frentree/pimcmac#12]
서비스는 설치 시(application에 앱이 설치가 된 직후) 자동으로 시작이 되도록
중지는 명령어 제공 또는 kill로 중지 할 수 있도록

P.S. 명령어 제공이 제일 베스트이긴 합니다.

**Comment by gonEH** [comment]
아래 명령으로 앱을 종료할 수 있습니다.
```
osascript -e 'quit app "PIMC"'
```
