### ISSUE TITLE
메뉴 정리

### ISSUE THREAD

**Issue by Frentree** [Frentree/pimcmac#13]
"버전 확인" 하나만 나올 수 있도록
웹페이지 접속 기능은 개발 후 hide 조치

차후 관리를 위해 서비스 점검 항목은 따로 열 수 있게 되면 좋을 거 같습니다.
만약 로그를 남기게 된다면 연결 해지에 대한 정보를 시간으로 남기며 10메가 미만으로 남기는 부분이 베스트 일 것 같습니다.

**Comment by gonEH** [comment]
웹 페이지 주소 부탁드립니다.

**Comment by gonEH** [comment]
서비스 점검 항목에 대해 구체적인 내용 전달 부탁드립니다.

**Comment by Frentree** [comment]
> 웹 페이지 주소 부탁드립니다.

해당 부분은 가이드 해주신대로 조치 진행 예정입니다.
감사합니다.
