### ISSUE TITLE
기능 문의 : 상태 점검 주기를 전역변수로 선언, 변경이 쉽게 되도록 가능한지

### ISSUE THREAD

**Issue by Frentree** [Frentree/pimcmac#16]
시연을 위한 짧은 주기용 하나, 실 사용을 위한 주기 하나가 필요한 상황입니다.

시연용으로는 10초 내지 1분으로 점검 주기가 필요할 것으로 보이고
실사용으로는 5분 주기로 설정이 필요합니다.
(타 솔루션은 10분 주기로 점검하지만, 실제로 점검할 시 보내는 패킷의 사이즈가 작은 관계로 5분 정도가 적합할 것으로 보입니다.)

**Comment by gonEH** [comment]
해당 이슈는 이미 `Constants.swift`에 구현 되어있습니니다.
