### ISSUE TITLE
버전정보를 텍스트로 관리 : Agent version, App version

### ISSUE THREAD

**Issue by Frentree** [Frentree/pimcmac#17]
현재 버전관리가 되어야 하는 포인트가 2군데이기 때문에(에이전트, 어플리케이션) 버전 관리가 부득이하게 텍스트로 이루어져야 될 것 같습니다.

예를 들어...
2.5.0-1.0.3
이런 식으로 <에이전트 버전>-<어플리케이션 버전> 이렇게 관리가 될까요?

**Comment by gonEH** [comment]
1. `info.plist` 에서 `Agent version` 을 추가하였습니다.
2. Agent version 값은 우선 제시해주신대로 `2.5.0` 으로 설정하였습니다. `info.plist` 에서 수정해주세요.
3. 각각 어떤 버전인지 헷갈릴 수도 있을 것 같아서 우선 아래와 같이 출력되도록 하였습니다.
```
Agent version : 2.5.0
App version : 1.0.0
```
