### ISSUE TITLE
상태 확인 프로세스 로직 추가

### ISSUE THREAD

**Issue by gonEH** [Frentree/pimcmac#2]
![image](https://user-images.githubusercontent.com/47036304/187106946-f783ab8d-7e54-4010-8389-e517649d86ee.png)
```
jeonjunhyeon@jeonjunhyeon-ui-Macmini ~ % 
jeonjunhyeon@jeonjunhyeon-ui-Macmini ~ % sudo /usr/local/er2/er2-config -i 192.168.0.37 -t
Master server is specifed as: 192.168.0.37
Testing connection setting...
Test SUCCESS. Saving settings
Configuration updated, please restart agent service
The configuration has been saved. Please restart the agent for the changes to take effect.
jeonjunhyeon@jeonjunhyeon-ui-Macmini ~ % 
```

![image](https://user-images.githubusercontent.com/47036304/187106987-0421dab9-d41a-4efe-ab06-e83c094b4002.png)
```
jeonjunhyeon@jeonjunhyeon-ui-Macmini ~ % 
jeonjunhyeon@jeonjunhyeon-ui-Macmini ~ % ps -aef | grep er2
  502 64424     1   0 10:47AM ??         0:00.10 /usr/local/er2/er2-agent -start -fg
  501 64949 63488   0 10:54AM ttys002    0:00.00 grep er2
jeonjunhyeon@jeonjunhyeon-ui-Macmini ~ % 
```

![image](https://user-images.githubusercontent.com/47036304/187107242-218f37a0-50e1-4662-b628-b3d1a75fdc91.png)

**Comment by Frentree** [comment]
프로세스 활성화 상태 체크하는 부분에서 (ps -aef | grep er2) 조금 더 디테일하게, 하나만 체크하는 방법으로
ps -aef | grep er2 | grep -v grep
이 있겠습니다.
pid를 통해 체크하시는 부분이 편하시다면 다음과 같은 위치에 pid 값이 저장되는 부분을 인지하고 계시면 쉬우실 것 같습니다.
cat /var/run/er2/agent.pid
